sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
env:
  - DB=sqlite DJANGO_PACKAGE=Django~=1.11
  - DB=postgres DJANGO_PACKAGE=Django~=1.11
  - DB=sqlite DJANGO_PACKAGE=Django~=2.0
  - DB=postgres DJANGO_PACKAGE=Django~=2.0
matrix:
  exclude:
    - python: "2.7"
      env: DB=sqlite DJANGO_PACKAGE=Django~=2.0
    - python: "2.7"
      env: DB=postgres DJANGO_PACKAGE=Django~=2.0
install: 'pip install $DJANGO_PACKAGE && pip install .'
script: make test SETTINGS=tests.travis_settings
before_script:
  - psql -c 'create database test_ool;' -U postgres
  - pip install psycopg2-binary 
