sudo: false
language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
env:
  - DB=sqlite DJANGO_PACKAGE=Django~=1.8
  - DB=postgres DJANGO_PACKAGE=Django~=1.8
  - DB=sqlite DJANGO_PACKAGE=Django~=1.9
  - DB=postgres DJANGO_PACKAGE=Django~=1.9
  - DB=sqlite DJANGO_PACKAGE=Django~=1.10
  - DB=postgres DJANGO_PACKAGE=Django~=1.10
install: 'pip install $DJANGO_PACKAGE --use-mirrors && pip install .'
script: make test SETTINGS=tests.travis_settings
before_script:
  - psql -c 'create database test_ool;' -U postgres
  - pip install psycopg2
